import { Conversation } from './conversation';

export const Conversations: Conversation[] = [
    {
        contactId: 1,
        contactAvatar: "./assets/images/Avatar/1.jpg",
        contactName: "Trung Trần",
        status: 1,
        time: new Date('2020/7/03 12:40:43'),
        amountNewMessage: 1,
        lastMessage: "nay họp em nhé",
        lastMessageStatus: 0,
    }, 
    {
        contactId: 2,
        contactAvatar: "../assets/images/Avatar/2.jpg",
        contactName: "Hoàng Cao Phi",
        status: 1,
        time: new Date('2020/7/03 12:40:43'),
        lastMessage: "hello",
        lastMessageStatus: 1,
    }, 
    {
        contactId: 3,
        contactAvatar: "./assets/images/Avatar/3.jpg",
        contactName: "Trần Hải Dương",
        status: 0,
        time: new Date('2020/7/02 12:40:43'),
        lastMessage: "nay đi đá bóng không?",
        lastMessageStatus: 1,
    }, 
    {
        contactId: 4,
        contactAvatar: "./assets/images/Avatar/4.jpg",
        contactName: "Đỗ Xuân Dũng",
        status: 0,
        time: new Date('2020/7/01 12:40:43'),
        amountNewMessage: 2,
        lastMessage: "chào bạn",
        lastMessageStatus: 0,
    }, 
    {
        contactId: 5,
        contactAvatar: "./assets/images/Avatar/1.jpg",
        contactName: "Nguyễn Văn Minh",
        status: 1,
        time: new Date('2020/6/21 12:40:43'),
        amountNewMessage: 2,
        lastMessage: "fix bug đi",
        lastMessageStatus: 0,
    }, 
]